model:
  name: template

task:
  name: template
  max_steps: 100_000
  train_dl:
    batch_size: 16

optimizer:
  name: adam
  lr: 3e-4

lr_scheduler:
  name: linear

trainer:
  name: sl

logger:
  - name: stdout
  - name: tensorboard

launcher:
  name: mp
