name: Python Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-base-tests:
    strategy:
        matrix:
            project_type: [vanilla, cpp]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Restore cache
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ env.pythonLocation }}
            .mypy_cache/
          key: python-requirements-${{ matrix.project_type }}-${{ env.pythonLocation }}-${{ github.event.pull_request.base.sha || github.sha }}
          restore-keys: |
            python-requirements-${{ matrix.project_type }}-${{ env.pythonLocation }}
            python-requirements-${{ matrix.project_type }}-

      - name: Initialize project
        run: |
          ./initialize \
            --name 'my_project' \
            --description 'My project description' \
            --author 'My Name' \
            --project ${{ matrix.project_type }} \
            --remove-init 1

      - name: Install package
        run: |
          pip install --upgrade --upgrade-strategy eager --extra-index-url https://download.pytorch.org/whl/cpu -e '.[dev]'

      - name: Run static checks
        run: |
          mkdir -p .mypy_cache
          make static-checks

      - name: Run unit tests
        run: |
          make test

      - name: Save cache
        uses: actions/cache/save@v3
        if: github.ref == 'refs/heads/master'
        with:
          path: |
            ${{ env.pythonLocation }}
            .mypy_cache/
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
